version: '3.8'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn soil_testing_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=['.localhost', '127.0.0.1', '.swansea.ac.uk']
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 


